### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by michou214** [cyberbotics/AROSYS#47]
To do:
- [x] Check if it is possible to use official PROTOs names for robots => #46 
- [x] Verify that all systems have the simple world and the complex world with right robot and official name => #49
- [x] Check the lidars that they are properly configured and placed in the robots => #49
- [x] Clean the `ComponentWebotsBumper` when we've merged the PR => #50
